import os

API_KEY_ACCES_LOCAL = os.environ['API_KEY_ACCESS_LOCAL']
API_KEY_AZURE_LLAMA = os.environ['API_KEY_AZURE_LLAMA']
API_KEY_AZURE_OPENAI = os.environ['API_KEY_AZURE_OPENAI']
AZURE_LLAMA_ENDPOINT = os.environ['AZURE_LLAMA_ENDPOINT']
AZURE_OPENAI_ENDPOINT = os.environ['AZURE_OPENAI_ENDPOINT']


if __name__ == "__main__":
    print (AZURE_LLAMA_ENDPOINT)